# Generated by Django 4.0.5 on 2022-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_status',
            new_name='complete',
        ),
    ]
