# Generated by Django 4.0.5 on 2022-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.FloatField(null=True),
        ),
    ]
