# Generated by Django 4.0.5 on 2022-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
