# Generated by Django 4.0.5 on 2022-08-14 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField()),
                ('branch_code', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('suburb', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Do not include country code, start with 0', max_length=10)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('background_image', models.ImageField(default='media/bg-images/default.jpg', upload_to='bg-images/')),
                ('description', models.TextField()),
                ('tag_line', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
