# Generated by Django 4.0.5 on 2022-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='background_image',
            field=models.ImageField(default='', upload_to='bg-images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='tag_line',
            field=models.CharField(default='', max_length=255),
        ),
    ]
