# Generated by Django 4.0.5 on 2022-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_background_image_shop_description_shop_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='background_image',
            field=models.ImageField(default='media/bg-images/default.jpg', upload_to='bg-images/'),
        ),
    ]
