# Generated by Django 4.0.5 on 2022-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shop_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address1',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='shop',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='post_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='suburb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
